Feat(SignUp): 카카오 회원가입, jwt 로그인 구현
Jabiseo/Jabiseo-Backend pull request #21
Opened 2024-07-11 07:25 UTC by InHyeok-J

## PR 변경된 내용

- idToken 기반 회원가입 / 로그인 기능 구현 (카카오 구현됨)
- Member Oauthserver type 수정
- jwt, oidc public key cache 적용
- usecase -> application 패키지로 auth쪽만 변경

## 추가 내용
- kakao의 idToken 검증을 https://developers.kakao.com/docs/latest/ko/kakaologin/common#oidc 기반 검증 도입
- 추후 google과 그 외 vender 사를 고려해 템플릿 메소드 패턴으로 적용
- kakao public key 캐싱 적용 (Redis Cache)
- jwt 발급 임의 구현(유효 기간, 안에 넣을 내용 등)

## 참조
- 한번에 구현한 양이 많아 google 로그인은 따로 issue를 받아서 처리할 예정(issue #20) 수정하겠습니다.
- 저번에 예기한 Auth 도메인 Token객체는 추후 논의 필요 (아무런 로직이 없는 것 같아서 제외시킴)
- Test코드는 PR올리고 추가로 작성해 올리겠습니다(오늘 5시 전에 PR 올리려고 미리 올렸음)

### 논의가 필요한 내용
- JWT의 정책(유효기간, 키 관리 등)

Closed: #20

2024-07-11 16:33 UTC, morenow98 requested changes
OIDC 쪽 코드를 너무 잘 짜신 것 같아요! 밑에 질문드린 게 좀 많지만,,,,
LGTM😁

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +public class LoginUseCase {
이 UseCase에 @Transactional은 필요 없는 건가요?

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/TokenValidatorManager.java
> +    private final Map<OauthServer, AbstractIdTokenValidator> validator = new HashMap<>();
이 변수명은 validator 들을 map 으로 모아놓은 거니까 그냥 validator로 하면 idTokenValidator 하고 혼동될 수도 있을 것 같아요. validators 혹은 validatorMap 정도도 괜찮을 것 같네요..!

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/KakaoIdTokenValidator.java
> +    private final String CACHE_KEY = "KAKAO_OIDC_PUBLIC_KEY";
저는 상수를 선언할 때는 static 도 붙이는 편인데, 혹시 붙이지 않는 이유가 따로 있을까요?
비록 싱글톤 객체의 상수이긴 하지만 static 을 붙임으로써 "클래스에 할당된 유일한 상수 값"이라는 관례적인 의미도 있다고 하더라구요. 
다른 사람들이 static final 을 봤을 때, "아 이건 모든 프로그램에서 단 하나의 값으로만 쓰이는 상수구나" 라는 의미로요.

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-infrastructure/src/main/java/com/jabiseo/cache/RedisCacheRepository.java
> +            operation.set(key, publicKeyString, 1, TimeUnit.DAYS);
public key 를 하루동안 저장하는 게 요구사항에 따라 바뀔 수도 있는 값이니까 환경 변수나 상수로 따로 관리하는 것도 좋아 보여요

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/KakaoIdTokenValidator.java
> +            OidcPublicKeyResponse publicKeys = kakaoKauthClient.getPublicKeys().getBody();
그럴 일은 잘 없겠지만 카카오 서버와 통신 과정에서 일어나는 예외도 처리하는 게 좋을 것 같아요

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-infrastructure/src/main/java/com/jabiseo/client/OidcPublicKeyResponse.java
> +@NoArgsConstructor
여기서 이 어노테이션들이 꼭 필요한 건가요?

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +    private static boolean isRequireSignup(Member member) {
static 인 이유가 있나요?

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/JwtHandler.java
> +                .compact();
여기서 payload 맵은 결국 쓰이지 않는 것 같은데, 나중에 있을 payload의 추가를 위해서 이렇게 한 건가요?

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/JwtHandler.java
> +package com.jabiseo.auth.application;
많이 회의했지만, JWT 같은 것에 대한 로직을 담당하는 클래스가 api 모듈에 있는 것이 맞는지 같은 것들은 나중에 다시 회의를 통해 더 나은 구조가 있다면 리팩토링 해봅시다~

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +        }
다른 식으로도 짜봤어요. 무조건 더 낫다는 게 아니라, 한 번 보시고 더 나은 것 같으면 바꿔도 좋을 것 같아요~

Member member = memberRepository.findByOauthIdAndOauthServer(oauthMemberInfo.getOauthId(), oauthMemberInfo.getOauthServer())
                .orElseGet(() -> {
                    Member newMember = memberFactory.createNew(oauthMemberInfo);
                    return memberRepository.save(newMember);
                });

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-common/src/main/java/com/jabiseo/exception/ErrorCode.java
> +        int AUTHENTICATION_ERROR = 401;
UNAUTHORIZED 가 좀 더 명확할 것 같아요..!

2024-07-11 16:33 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/member/domain/RandomNicknameGenerator.java
> +    private static final String[] prefixStrings = {"자격증마스터", "공부의왕", "백점만이살길", "하루공부", "재밌는자격증"};
이것도 나아중엔 따로 enum 등으로 관리하는 게 좋아보이네요..!

2024-07-12 02:05 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/JwtHandler.java
> +                .compact();
예 맞습니다

2024-07-12 02:05 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/member/domain/RandomNicknameGenerator.java
> +    private static final String[] prefixStrings = {"자격증마스터", "공부의왕", "백점만이살길", "하루공부", "재밌는자격증"};
해당 prefix는 한번 예기해보고 괜찮으면 추후에 관리해볼게요~

2024-07-12 02:06 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +public class LoginUseCase {
적용했습니다

2024-07-12 02:09 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/TokenValidatorManager.java
> +    private final Map<OauthServer, AbstractIdTokenValidator> validator = new HashMap<>();
적용했습니다

2024-07-12 02:10 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/KakaoIdTokenValidator.java
> +    private final String CACHE_KEY = "KAKAO_OIDC_PUBLIC_KEY";
좋은 의견이네요 ! 적용했습니다

2024-07-12 02:12 UTC, InHyeok-J commented on jabiseo-infrastructure/src/main/java/com/jabiseo/cache/RedisCacheRepository.java
> +            operation.set(key, publicKeyString, 1, TimeUnit.DAYS);
해당 부분 관련해서 아무런 정의된게 없어서 임의의 숫자를 넣었습니다 이거에 대해 따로 논의해보죠

2024-07-12 02:17 UTC, InHyeok-J commented on jabiseo-infrastructure/src/main/java/com/jabiseo/client/OidcPublicKeyResponse.java
> +@NoArgsConstructor
네 jackson 라이브러리 동작을 위해 필요한 어노테이션입니다

2024-07-12 02:17 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +    private static boolean isRequireSignup(Member member) {
수정하겠습니다

2024-07-12 02:21 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/JwtHandler.java
> +package com.jabiseo.auth.application;
좋습니다 오늘 마저 얘기해보죠!

2024-07-12 02:24 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/usecase/LoginUseCase.java
> +        }
람다랑 스트림을 잘 사용하시네요~ 좋은것 같습니다

2024-07-12 02:27 UTC, InHyeok-J commented on jabiseo-common/src/main/java/com/jabiseo/exception/ErrorCode.java
> +        int AUTHENTICATION_ERROR = 401;
좋은 의견입니다

2024-07-12 02:28 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/auth/application/oidc/KakaoIdTokenValidator.java
> +            OidcPublicKeyResponse publicKeys = kakaoKauthClient.getPublicKeys().getBody();
원래 이부분을 kakao client에 config 설정과 동시에 처리하고 싶었는데 공부가 필요할 것 같네요
일단은 코드레벨에서 처리를 진행해보겠습니다

2024-07-12 03:06 UTC, morenow98 commented on jabiseo-infrastructure/src/main/java/com/jabiseo/cache/RedisCacheRepository.java
> +            operation.set(key, publicKeyString, 1, TimeUnit.DAYS);
TODO 같은 걸 표시해줄 수 있나요?

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/common/EnumValid.java
> +@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })
실제 사용되는 곳은 필드 뿐인 것 같은데 다른 타겟은 왜 있는 건지 궁금합니다. 다양한 곳에서 쓸 수 있도록 남겨 놓은 건가요?

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/common/EnumValid.java
> +package com.jabiseo.common;
검증을 하는 어노테이션의 위치가 api 모듈이 맞는 건지, domain 모듈이 맞는 건지 잘 모르겠네요..! 나중에 구조를 또 얘기해보죠

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/common/ValueOfEnumValidator.java
> +        return result;
아래와 같이 짜봤는데 괜찮다면 반영해주셔도 좋을 것 같아요!~
1. result 변수 삭제
2. enumValues null 체크 early return
```suggestion
        if(value == null){
            return false;
        }

        Enum<?>[] enumValues = this.enumValid.enumClass().getEnumConstants();

        if (enumValues == null) {
            return false;
        }
        for (Object enumValue : enumValues) {
            if (value.equals(enumValue.toString())
                    || this.enumValid.ignoreCase() && value.equalsIgnoreCase(enumValue.toString())) {
                return true;
            }
        }
        return false;
```

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-api/src/test/java/com/jabiseo/auth/application/usecase/LoginUseCaseTest.java
> +    @DisplayName("처음 요청 오는 OAuth 회원일시 맴버 객체를 생성하고 저장한다.")
별건 아니지만,,, 맴버 -> 멤버,,, 😂

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-api/src/test/java/com/jabiseo/auth/dto/LoginRequestTest.java
> +    @DisplayName("login 요청시 idToken에 숫자가 오면 예외를 반환한다,")
ID Token 에 대한 테스트가 아니라 OauthServer 값에 대한 테스트인 거 아닌가요?

2024-07-13 11:13 UTC, morenow98 commented on jabiseo-infrastructure/src/main/java/com/jabiseo/client/RestClientConfig.java
> +                }))
👍

2024-07-15 02:14 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/common/EnumValid.java
> +@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })
넵 맞습니다!

2024-07-15 03:17 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/common/EnumValid.java
> +package com.jabiseo.common;
좋습니다!

2024-07-15 03:17 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/common/ValueOfEnumValidator.java
> +        return result;
좋은 의견입니다 훨씬 depth가 줄어들었네요

2024-07-15 03:17 UTC, InHyeok-J commented on jabiseo-api/src/test/java/com/jabiseo/auth/dto/LoginRequestTest.java
> +    @DisplayName("login 요청시 idToken에 숫자가 오면 예외를 반환한다,")
맞습니다 수정했습니다 ㅠㅠ

2024-07-15 03:27 UTC, morenow98 approved these changes

2024-07-15 03:29 UTC, merged