Feat(Problem): 북마크한 문제 목록 조회 API 구현
Jabiseo/Jabiseo-Backend pull request #28
Opened 2024-07-22 09:26 UTC by morenow98

## PR 변경된 내용
### 북마크한 문제 목록 조회 API 구현
1. 일부 검증의 책임을 각 도메인으로 이전, 이후 검증만을 책임지는 Validator 혹은 DTO의 Valid 어노테이션 활용으로 리팩토링 가능성 있음.
2. examId의 존재 유무에 따라 문제를 찾는 로직이 복잡함에 따라 관심사의 분리가 필요. 따라서 domain 모듈에 해당 로직을 담당하는 Service 클래스 구현

## 추가 내용
- Problem에서 Bookmark를 참조하는 경우가 없어 양방향 매핑을 하지 않도록 변경
- Problem에서 생성 시 createdAt 값이 생성되지 않는 현상 수정
- 문제 풀이에서 과목당 문제 수가 최소한 1개는 되어야 하는 것으로 수정
- Jira에서 Github로 이전하면서 pull request template 변경

## 참조
Closes #19

2024-07-23 03:19 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +        }
contains라는 네이밍이 메소드 행위랑 안맞는거 같아서 현재 자격증 상태가 등록돼있는지를 판단하는 네이밍이 적용되면 좋을거같습니다(ListX)

2024-07-23 04:54 UTC, InHyeok-J requested changes
다시 리뷰주세요

2024-07-23 04:54 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +        List<Problem> problems = bookmarkedProblemService.findBookmarkedProblems(problemIds, examId, subjectIds, pageable);
이거 수정 필요

2024-07-23 04:54 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +
해당 메소드의 책임을 정리해봤는데
1. 검증
    - 현재 자격증을 갖고 있는지 확인하고
    - 갖고 있으면 그 자격증 기반으로 입력받은 subjects가 정확한지 검증하고
    - exam까지 정확한지 검증한다
2. 쿼리
    - 이후 examid 여부에 따라
    - 다른 2가지 쿼리를 날린다.
    - if queryDSL이라면 where null인거 자동 체크해줄텐데…
    
  라고 생각합니다. 
  코드에 고민이 있는거같은데 크게 이렇게 2개 뽑아서 한번 분리해보는건 어떨까요?

2024-07-23 04:54 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/problem/service/BookmarkedProblemService.java
> +    }
메소드 examId에 따라서 분기 처리해서 다른 쿼리를 날리는게 핵심 책임인것 같은데

이러면 if가 있는게 직관적으로 좋은 거 같습니다

2024-07-23 04:54 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
validate가 아니라 contains으로 처리하고 
validate 메소드 안에 2개를 호출하는게 어떠세요?

```java
public void validateContainsSubjectAndExam(List subjects, Optional exam){
    this.containsSubjects(subjects);
    this.containsExam(exam);
}

private void containsSubjects(){}
private void containsExam(){}
```
2개를 호출하는게 같이 가니깐 하나로 묶어도 좋을거같아요

2024-07-25 09:23 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +        }
has 메소드 명으로 바꿨습니다

2024-07-25 09:24 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +        List<Problem> problems = bookmarkedProblemService.findBookmarkedProblems(problemIds, examId, subjectIds, pageable);
수정해서 올렸습니다

2024-07-25 09:24 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCase.java
> +
수정해서 올렸습니다.

2024-07-25 09:25 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/problem/service/BookmarkedProblemService.java
> +    }
수정해서 올렸습니다.

2024-07-25 09:25 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
수정해서 올렸습니다.

2024-07-25 13:38 UTC, InHyeok-J requested changes
TestFixtures는 처음보는데 좋네요 GOOD
댓글 단거 몇개 있는데 이거 내일 얘기해보자

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/member/domain/Member.java
> +    }
Member에 현재 진행중인 자격증이 없으면 예외를 반환시켜야 하나?
이거에 관한 API 문서에 정의는 없는데 FindMyCertificateStateResponse 클래스 보면 of 메소드 안에 null 인경우 null로 리턴하는 코드로 구현중인데 해당 부분 동기화 작업이 필요할듯
그리고 이 코드가 테스트가 통과된건 FindCertificateUseCase에 null 인경우 빈 값을 넣는거를 테스트 안하는데 테스트가 필요해보임.

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/member/exception/MemberErrorCode.java
> +    CURRENT_CERTIFICATE_NOT_EXIST("자격증 상태가 존재하지 않습니다.", "MEM_002", ErrorCode.BAD_REQUEST),
해당 코드가 400예외를 갖는 이유가 뭐지? client의 예외는 아닌거같은데

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-domain/src/test/java/com/jabiseo/problem/domain/ProblemRepositoryTest.java
> +    void givenProblemConditions_whenFindingBookmarkedProblems_thenFindBookmarkedProblems() {
해당 JPA 쿼리를 직접 jpql로 짜서 테스트 하는건 좋은듯
근데  Displayname으로는 무엇을 테스트하려고 하는지 알수가 없는거같아 이거 구체화 가능?

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
validateAndSubjectIds메소드에서 exam 이 파라미터가 있는데 빠진거같음 오타인거같은데?

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
@morenow98 public하게 노출이 안되는건 일단 private 으로 두는건 어떄

2024-07-25 13:38 UTC, InHyeok-J commented on jabiseo-api/src/test/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCaseTest.java
> +        String memberId = "1";
음 해당 테스트코드를 열심히 짰는데 실패 케이스에 대한건 Usecase에서 테스트를 안하나? 
안하면 Certificate 의 도메인 Pojo 테스트라도 추가하면 좋을듯
그리고 성공 케이스에 대해 많이 짰는데 실패 케이스를 먼저 테스트해서 짜는건 어때?

2024-07-25 13:42 UTC, InHyeok-J commented
@morenow98 usecase패키지로 남아있는데 application으로 패키지 네이밍 통일해서 올려줘

2024-07-25 14:32 UTC, morenow98 commented on jabiseo-domain/src/test/java/com/jabiseo/problem/domain/ProblemRepositoryTest.java
> +    void givenProblemConditions_whenFindingBookmarkedProblems_thenFindBookmarkedProblems() {
굳굳 수정했어

2024-07-25 14:32 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 정신이 없었나보다...

2024-07-25 15:47 UTC, morenow98 commented on jabiseo-api/src/test/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCaseTest.java
> +        String memberId = "1";
이 유스케이스에서 경우의 수는 다음 경우가 있는데,
1. 성공
2. 멤버가 현재 자격증을 가지고 있지 않을 경우
3. examId와 subjectId가 올바르지 않을 경우
4. repository에서 쿼리가 제대로 동작하지 않을 경우

맨 처음에는 1,2,3 번에 대한 테스트를 usecase에서 짰어. 근데 구현이 변경되면서 1번만 남았고, 4번은 추가로 @DataJpaTest 를 통해서 구현했어.

2,3번이 구현되어 있지 않아서 추가로 구현해서 지금 올렸어.
2번은 그대로 UseCase 에 추가로 구현했고, 3번의 검증 책임을 Certificate 클래스로 옮긴 상태라서 테스트코드도 그 메소드를 테스트했어

2024-07-25 15:59 UTC, morenow98 commented on jabiseo-api/src/test/java/com/jabiseo/problem/usecase/FindBookmarkedProblemsUseCaseTest.java
> +        String memberId = "1";
완전 깜빡한 부분인데 떙큐

2024-07-25 16:34 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/problem/service/BookmarkedProblemService.java
> +    }
UseCase 에 보면 if(examId.isPresent()) 로 올려놨는데 두 코드 비교해서 어떤 게 나은지 봐봐

```java
if (examId.isPresent()) {
    return problemRepository.findBookmarkedByExamIdAndSubjectIdIn(memberId, examId.get(), subjectIds, pageable)
            .stream()
            .map(FindBookmarkedProblemsResponse::from)
            .toList();
} else {
    return problemRepository.findBookmarkedBySubjectIdIn(memberId, subjectIds, pageable)
            .stream()
            .map(FindBookmarkedProblemsResponse::from)
            .toList();
}
```

```java
List<Problem> problems = examId.map(id ->
                problemRepository.findBookmarkedByExamIdAndSubjectIdIn(memberId, id, subjectIds, pageable))
        .orElseGet(() -> problemRepository.findBookmarkedBySubjectIdIn(memberId, subjectIds, pageable));

return problems.stream()
        .map(FindBookmarkedProblemsResponse::from)
        .toList();
```

2024-07-25 16:34 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/certificate/domain/Certificate.java
> +    }
수정 완료

2024-07-26 03:10 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/problem/service/BookmarkedProblemService.java
> +    }
지금보니 둘다 좋은데? 너가 편한거 선택하면 될듯

2024-07-26 04:12 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/problem/service/BookmarkedProblemService.java
> +    }
아래 걸로 올렸음

2024-07-26 04:42 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/member/exception/MemberErrorCode.java
> +    CURRENT_CERTIFICATE_NOT_EXIST("자격증 상태가 존재하지 않습니다.", "MEM_002", ErrorCode.BAD_REQUEST),
회의 결과 보내면 안되는 상황에서만 나는 오류이므로 400이 맞는 것으로~

2024-07-26 04:42 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/member/domain/Member.java
> +    }
validate 하는 메소드를 따로 분리해서 구현해서 올렸음

2024-07-26 04:45 UTC, InHyeok-J approved these changes
Member POJO Test 하면 더 좋을거 같음 고생했으

2024-07-26 04:49 UTC, morenow98 commented
> Member POJO Test 하면 더 좋을거 같음 고생했으
해서 올렸음~!

2024-07-26 04:50 UTC, merged