Feat(Plan): 플랜 entity, 생성, 조회 구현
Jabiseo/Jabiseo-Backend pull request #65
Opened 2024-09-06 03:00 UTC by InHyeok-J

## PR 변경된 내용
- Plan Entity 구성
- 결과 제출 후 PlanProgress 생성
- 플랜 생성, 조회 로직 구현

### Plan Entity 구성
- 학습 플랜의 요구사항에 맞게 Entity 구성 (https://github.com/orgs/Jabiseo/discussions/64) 양이 많아 따로 올림
- Learning에 Member가 없던 부분 추가

### 결과 제출 후 PlanProgress 생성
- PlanProgressService에 updateProgress() 메소드 호출
- (1) 진행중인 플랜이 있는지 확인
- (2) PlanProgress가 DB에 있는지 확인, 없으면 생성해줘야 함(문제를 제출했으면 날짜범위(일간,주간)에 0인 값이라도 DB에 있어야 한다)
- (3). 이후 결과 제출 데이터 기반으로 PlanProgress 업데이트

### 플랜 생성
- (1): 진행중인 자격증/ 플랜이 있는지 확인
- (2): DB에 저장후 현재 문제풀이 기록(Learning와 ProblemsSolving) 기반으로 현재날짜(일간은 오늘, 주간은 주 범위)에 데이터가 있다면 PlanProgress을 생성한다.
- 추가적으로 Learning과 ProblemSolving 정보를 가져오는 쿼리는 일간/주간에 따라 일단 2개 분기로 처리해서 날림

### 플랜 조회
- PlanProgress 정보를 읽어와서 일간 / 주간에 따라 리턴함.
- 주간같은 경우 달의 첫날, 마지막 날이 아닌 첫주 마지막 주는 그 전달, 그 이후 달의 날짜 범위가 포함될 수 있다.
- 해당 부분을 한 곳에서 관리하기 위해 SundayStratWeeklyStrategy라는 클래스에서 날짜 관련 메소드를 제공함.

### 기타
- Plan쪽은 대부분 Service라는 클래스를 생성해서 로직을 분리함
- 플랜 수정은 다음 PR에 진행 예정( 기업 지원 이슈 )

## 참조
Closes #56

2024-09-06 17:30 UTC, morenow98 requested changes
고생한 게 너무 보이는 PR이다 ㅋㅋㅋㅋㅋㅋ... 코드량이 많아서 한참 리뷰하느라 리뷰 개수도 많아.. 코드 잘 짠 것 같네 LGTM😁

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/WeeklyDefineStrategy.java
> +    WeekPeriod getCurrentWeekPeriod(LocalDate now);
이 메소드가 현재의 WeekPeriod를 반환하는 건데 파라미터에 옛날 LocalDate가 들어가면 그 시점의 WeekPeriod가 반환될 수 있을 것 같아.
getCurrentWeekPeriod() -> 오늘의 WeekPeriod를 반환
getWeekPeriod(LocalDate localDate) -> localDate 시점의 WeekPeriod를 반환
이 둘 중에 하나가 되어야 할 것 같아.

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/ActivityType.java
> +    EXAM, STUDY, PROBLEM, TIME
이렇게만 봐서는 각 항목이 어떤 액티비티인지 알 수 없을 것 같아. 
EXAM 은 LearningMode의 EXAM하고 헷갈려서, EXAM_COUNT라던가, LEARNING_TIME 같이 살짝 더 구체적이면 좋지 않을까 싶은데
아니면 관련된 설명을 description 변수 등으로 추가한다거나 주석으로 간단하게 달면 읽기 좋을 거 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanService.java
> +        planItemRepository.saveAll(planItems);
이 부분에서 한 번에 많은 데이터가 insert 되는데 Batch Insert를 활용해도 좋을 듯. JPA에선 IDENTITY 전략을 사용할 때 Batch Insert를 지원하지 않는 걸로 알고 있는데, 우린 이 전략을 사용하지 않으니까, 딱 맞게 사용할 수 있고, 성능 개선에 좋을 것 같아.

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/dto/CreatePlanRequest.java
> +        @Future
여기도 @NotNull 필요하네. 잘못된 형태로 넣어서 테스트해봤더니 null인 채로 실행됐어.

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +                map.put(ActivityType.EXAM, planProgress);
이 map.put() 구문을 하지 않아도, 맵 안에 있는 PlanProgress 객체의 completedValue는 이미 증가한 게 반영되어 있을 거니까 없애도 될 것 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +        // 없으면 진행하지 않는다.
이 주석을 "PlanProgress로 전환할 PlanItem이 없는 경우 PlanProgress를 생성하지 않는다" 로 바꿔주면 좋을 것 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +        }
이 부분에도 주석을 "해당하는 기간에 학습를 하지 않았으면 PlanProgress를 생성하지 않는다" 같은 식으로 달아주면 좋을 것 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +        List<PlanProgress> planProgresses = calculateProgress(progress, queryResult);
이 부분에는 주석을 "플랜 생성 전, 해당 기간에 학습을 진행했으므로 PlanProgress를 생성한다" 같은 식으로 달아주면 좋을 것 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +    public void createCurrentPlanProgress(Member member, List<PlanItem> planItems) {
이 메소드의 의미를 파악하기가 살짝 어려웠어. 메소드명을 조금만 더 정확하게 개선하거나, 주석을 "플랜 생성 시, 설정된 플랜 기간 중에 학습한 기록이 있다면 반영한다" 와 같은 식으로 달아주면 좋을 것 같아

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/controller/PlanController.java
> +        return ResponseEntity.ok(result);
여기서 member를 사용하지 않아. member의 plan인지 확인하고, 아니라면 403 오류 뱉는 검증 로직 추가되어야 해

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +        Plan plan = planRepository.getReferenceById(planId);
내가 getReferenceById를 사용한 부분은, @AuthMember 어노테이션을 통해 이미 member가 데이터베이스에 있는 것을 시큐리티에서 확인하고 온 memberId의 경우에만 썼던 거였어.
이렇게 getReferenceById를 쓰면 사용자가 planId를 이상하게 적어서 보내준 경우에 예외처리가 안돼. findById().orElseThrow() 로 예외처리 해줘야 할 것 같아.

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/SundayStartWeeklyStrategy.java
> +public class SundayStartWeeklyStrategy implements WeeklyDefineStrategy{
"주"의 기준을 Sunday로 결정했는데 한 번 추상화해서 Sunday에 의존하지 않게 처리한 게 너무 좋다

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +public class PlanCalenderSearchUseCase {
우리가 UseCase 이름을 전부 동사로 시작했으니까 SearchPlanCalenderUseCase 가 맞지 않을까?

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +        List<PlanProgress> progress = planProgressService.findByYearMonth(plan, year, month);
별 건 아니지만 progressList나 progresses로 하면 더 좋을 듯!

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +                .collect(Collectors.groupingBy(PlanProgress::getProgressDate, Collectors.toList()));
오우 스트림 활용 굿

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/dto/calender/PlanProgressResponse.java
> +    Long completedValue;
다른 DTO들 전부 record인데 얘만 class 라서 바꾸는 게 좋을 듯

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-domain/src/main/java/com/jabiseo/learning/domain/querydsl/LearningQueryDslRepositoryImpl.java
> +                        learning.mode,
나중에 실행계획 분석은 해봐야 할 듯!

2024-09-06 17:30 UTC, morenow98 commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +                    return PlanProgressDateResponse.ofWeek(findIndexWeek(weekPeriods, entry.getKey()) + 1, list);
여기서 +1은 왜 한 건지 잘 모르겠네.. 학습한 날의 다음날이 몇 번째 주인지 찾는 게 되는 거 아닌지 모르겠어..

2024-09-07 02:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/WeeklyDefineStrategy.java
> +    WeekPeriod getCurrentWeekPeriod(LocalDate now);
2번으로 조질게

2024-09-07 02:38 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanService.java
> +        planItemRepository.saveAll(planItems);
지금은 어쩔수 없고 인터페이스로 분리하고 구현체를 갈아끼워야 할거같아

2024-09-07 02:40 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/ActivityType.java
> +    EXAM, STUDY, PROBLEM, TIME
간단하게 해결할거면 노션의 문서화된 내용을 참고하는게 좋을거같아

2024-09-07 02:43 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/PlanProgressService.java
> +                map.put(ActivityType.EXAM, planProgress);
굳굳

2024-09-07 03:18 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/plan/controller/PlanController.java
> +        return ResponseEntity.ok(result);
굳굳 추가했어

2024-09-07 03:19 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +        Plan plan = planRepository.getReferenceById(planId);
이건 놓친거같은데 좋은데 굳굳

2024-09-07 03:24 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/plan/domain/SundayStartWeeklyStrategy.java
> +public class SundayStartWeeklyStrategy implements WeeklyDefineStrategy{
굳굳 감사요

2024-09-07 03:25 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +public class PlanCalenderSearchUseCase {
굳굳

2024-09-07 03:27 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/plan/dto/calender/PlanProgressResponse.java
> +    Long completedValue;
오키요

2024-09-07 03:28 UTC, InHyeok-J commented on jabiseo-domain/src/main/java/com/jabiseo/learning/domain/querydsl/LearningQueryDslRepositoryImpl.java
> +                        learning.mode,
추후에 하겠습니다

2024-09-07 03:37 UTC, InHyeok-J commented on jabiseo-api/src/main/java/com/jabiseo/plan/application/usecase/PlanCalenderSearchUseCase.java
> +                    return PlanProgressDateResponse.ofWeek(findIndexWeek(weekPeriods, entry.getKey()) + 1, list);
인덱스가 1부터 시작해서 그럼

2024-09-07 03:41 UTC, morenow98 approved these changes
굿굿!

2024-09-07 03:41 UTC, merged